### ISSUE TITLE
ZCatalog (ZMI) tab "Catalog"

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.ZCatalog#107]
I ran into some ZCatalog problems updating a Python 2 ZODB to Python 3 (on Zope 4.2.1), so I wanted to test the basic functionality of ZCatalog: I used to populate the ZCatalog with the tab "Find Objects" in the ZMI, so that's what I tried first. The update "worked":

    Catalog Updated
    Total time: 0.0002162456512451172
    Total CPU time: 0.00021599999999999397 (2020-05-05 15:01)

followed by `There are no objects in the Catalog.`

Of course there were objects to catalog in the catalog's path. I then created an index and some Metadata and tried again: in the "Index" tab I can see some indexes, so there are elements in the Catalog, but nothing is shown in the "Catalog" tab: `There are no objects in the Catalog.`

**Comment by dataflake** [comment]
Moved the issue to the correct repo

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2020-6-18 08:41 -0700:
>I ran into some ZCatalog problems updating a Python 2 ZODB to Python 3 (on Zope 4.2.1), so I wanted to test the basic functionality of ZCatalog: I used to populate the ZCatalog with the tab "Find Objects" in the ZMI, so that's what I tried first. The update "worked":
>
>    Catalog Updated
>    Total time: 0.0002162456512451172
>    Total CPU time: 0.00021599999999999397 (2020-05-05 15:01)
>
>followed by `There are no objects in the Catalog.`
>
>Of course there were objects to catalog in the catalog's path. I then created an index and some Metadata and tried again: in the "Index" tab I can see some indexes, so there are elements in the Catalog, but nothing is shown in the "Catalog" tab: `There are no objects in the Catalog.`

This problem is known -- it affects catalogs without index named "path".

There is a pull request to fix the problem -- waiting to be approved.

**Comment by icemac** [comment]
Claimed to be fixed by #104. So closing it here.
