### ISSUE TITLE
refactor brain instantiation code in Catalog.py

### ISSUE THREAD

**Issue by eprigorodov** [zopefoundation/Products.ZCatalog#11]
`Catalog.py` has three "Do Repeat Yourself" code blocks that create instances of search results (a.k.a. brain records).

Two almost identical blocks (let's name them **b1** and **b2**) are located in `Catalog.__getitem__()` and in `getScoredResult()` (nested in `Catalog.search()`). They initialise brain instance, fill in search score data and return result wrapped in acquisition context of parent ZCatalog (`r.__of__(aq_parent(self))`).

Third smaller block (**b3**) is defined in `Catalog.instantiate()` and is only called from `Catalog.search()` in one specific case: in queries that should return full catalog contents by iterating through its `self.data.items()`. It does not process score data and returns result wrapped in Catalog context (via `r.__of__(self)`).

Code in (**b1**) and (**b2**) is covered extensively by numerous unit tests, refactoring would not require additional test cases.

Code in (**b3**) is not called from current test suite. There is a test that queries full catalog contents (`test_catalog.TestCatalogReturnAll.testEmptyMappingReturnsAll()`), but it does not try to iterate through results, only calculates their count.

Proposal:

1. Extend signature of `Catalog.instantiate()` to `instantiate(self, record, score_data=None)`. Require that `score_data` contains a tuple of `(score, normalized_score)`. The method is internal so interface remains intact, new signature will remain compatible with the usage from (**b3**).
2. Modify `test_catalog.TestCatalogReturnAll.testEmptyMappingReturnsAll()` so it iterates through result set and examines individual brain records, thus calling `Catalog.instantiate()` without score data.
3. Extend implementation of `Catalog.instantiate(`) to support saving score data (if it is given) in the new brain instance. For compatibility reasons keep returning` r.__of__(self)` if score data was not passed (**b3**) or `r.__of__(aq_parent(self))` if it was (**b1** and **b2**).
4. Replace brain creation code in (**b1**) and (**b2**) with calls to `Catalog.instantiate()`.

**Comment by hannosch** [comment]
Excellent idea work! I merged your PR via a squashed commit 8ab5ebe2421461e7015940568b0fcc72f56fd2f6.
