### ISSUE TITLE
New release 5.x?

### ISSUE THREAD

**Issue by wesleybl** [zopefoundation/Products.ZCatalog#134]
Can we also have a `5.x` branch release, and possibly add it to `Zope 4`?

**Comment by icemac** [comment]
I am looking into creating this release.

**Comment by icemac** [comment]
When #144 is merged a release can be cut.

**Comment by icemac** [comment]
I just released https://pypi.org/project/Products.ZCatalog/5.4/. Until the next update of dependencies in Zope 4, you can pin to 5.4 in your project's version pins.
