### ISSUE TITLE
Stale cached results after clearing catalog index

### ISSUE THREAD

**Issue by davisagli** [zopefoundation/Products.ZCatalog#19]
An index's counter is used as part of its cache key in the request cache that was added in version 3.2. Clearing an index resets the counter, but it doesn't clear the request cache. As a result, queries after clearing the index may get stale results that were cached before the index was cleared.

This is causing a failure in at least one Plone test that does query when there is no content (counter = 0), then adds content and queries (counter = 1), clears and rebuilds the catalog (counter = 0), and does the query again (counter = 0 so gets the cached results, which are missing the content item that was added and still exists).

/cc @andbag

**Comment by andbag** [comment]
Issue should have already been solved in PR #17 (s. commit [9bd0d7ddf](https://github.com/zopefoundation/Products.ZCatalog/pull/17/commits/9bd0d7ddf7ff57ec6b3dc3b3adb858567580ddf3)).

@hannosch 
cherry-pick 9bd0d7ddf to master branch?

**Comment by hannosch** [comment]
Sorry for being inactive on ZCatalog. I spent my free time on Zope itself lately. I'll take a look once I'm back from a conference in a week. Unless someone else wants to volunteer before that :)

**Comment by hannosch** [comment]
I've cherry-picked the commit to master and the 3.x branch. I'll leave this open until I cut a 3.2.1 release. I'll do that once the current Zope sprint in Innsbruck is over, to not interfere with the sprinters work.

**Comment by hannosch** [comment]
ZCatalog 3.2.1 is up on PyPi for a while now.
