### ISSUE TITLE
brains can no longer acquire the request

### ISSUE THREAD

**Issue by pbauer** [zopefoundation/Products.ZCatalog#27]
When using the current zope master `aq_get(brain, 'REQUEST')` fails with a AttributeError. 
See https://github.com/plone/plone.app.contentlisting/pull/24

**Comment by hannosch** [comment]
My guess is that this isn't a ZCatalog problem, but rather something in five.localsitemanager. If you look up something via a getUtility call, the Acquisition chain magically vanishes as part of these lookups. So if you look up the catalog as a CMF tool (now utility), there's no Acquisition chain.

There's a whole lot of wrap/rewrap code in https://github.com/zopefoundation/five.localsitemanager/blob/master/src/five/localsitemanager/registry.py which tries to put back a Acquisition chain based on the portal/site. My guess is something with this part goes wrong now.

**Comment by pbauer** [comment]
Ok, I see that ZCatalog also uses zope.globalrequest in https://github.com/zopefoundation/Products.ZCatalog/blob/master/src/Products/ZCatalog/CatalogBrains.py#L46.
