### ISSUE TITLE
Make query planner configurable

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/Products.ZCatalog#3]
Here at der Freitag (http://www.freitag.de) we faced a huge performance problem: the query planner, to create the plan was trying to load all objects on the indexes, this should not be a problem if the database is not so big, but in our case we have **~3 million** objects on the main database and **~7 million objects** on the portal_catalog mount point.

We tried to use the master branch with Hanno's https://github.com/zopefoundation/Products.ZCatalog/commit/3b2f2f1b42e5a51c71c337e052f76586e501776e patch but that was still making our instances to take an awful amount of time to start.

In the end @ctheune wrote a quick patch to completely disable the query planner: https://github.com/ctheune/Products.ZCatalog/commit/fd4db1c9fa5b4bc37e6b95ca5df02596412bff3a

He tried to apply it on top of current master but without luck, still that commit is a quick hack, that's why I'm opening this issue, to ask if it would make sense to make the query planner configurable so that users can opt-out of it.

We are using Plone 4.2.6 with Products.ZCatalog 2.13.26
I would be glad to help on providing more information if needed.

**Comment by hannosch** [comment]
Closing this as no new information was given in almost two years ;)

**Comment by ctheune** [comment]
Wow. I didn't even notice this was still open. I'm seeing @gforcada in two weeks, maybe he wants to pick this up again if this is still an issue ... :)
