### ISSUE TITLE
2.13.28 buildout failed - no CHANGES.TXT

### ISSUE THREAD

**Issue by flipmcf** [zopefoundation/Products.ZCatalog#30]
Unpacking Products.ZCatalog-2.13.28/src/Products.ZCatalog.egg-
info/dependency_links.txt to /tmp/easy_install-
_LZ6QJ/Products.ZCatalog-2.13.28/src/Products.ZCatalog.egg-
info/dependency_links.txt
Running Products.ZCatalog-2.13.28/setup.py bdist_egg --dist-dir /tmp
/easy_install-_LZ6QJ/Products.ZCatalog-2.13.28/egg-dist-tmp-s9Stbu
error: [Errno 2] No such file or directory: 'CHANGES.txt'
An error occured when trying to install Products.ZCatalog 2.13.28. Look
above this message for any errors that were output by easy_install.

**Comment by flipmcf** [comment]
Is this a problem with the package?  2.13.27 installs just fune

**Comment by jamadden** [comment]
Yes, 2.13.28 [was broken](https://github.com/zopefoundation/Products.ZCatalog/commit/bd9735ec594b112dc82f9b9b1efdded399fc2cc1). There's already a new release of 2.13.29 that should be fixed.

**Comment by flipmcf** [comment]
Thanks.  Sorry for spam
