### ISSUE TITLE
Clean up code and `DeprecationWarnings`

### ISSUE THREAD

**Issue by sallner** [zopefoundation/Products.ZCatalog#37]
As in zopefoundation/Zope#268 we want to get rid of deprecation warnings. 

@andbag you already worked on branch (https://github.com/zopefoundation/Products.ZCatalog/tree/andbag-fix-deprecation) on that one. Would you mind to rebase and create a PR for that branch or do you have any intend to work longer on that?

**Comment by andbag** [comment]
PR created on https://github.com/zopefoundation/Products.ZCatalog/pull/38

**Comment by icemac** [comment]
#38 was merged.
