### ISSUE TITLE
New release 3.1.0.1 based on 3.1to fix raised TypeError and still rely on ZODB3

### ISSUE THREAD

**Issue by gbastien** [zopefoundation/Products.ZCatalog#40]
Hi,

I would like to release a version 3.1.0.1 based on version 3.1 but with the fix regarding raising a TypeError when index is None (backport the "#5: Ignore None values in UnIndex instead of raising a TypeError." fix).

Indeed for now, for example in last Plone 5.1.x release, it is not possible to use version 3.1 because of this blocking and it is no more possible to use version 3.1.1 because it relies on ZODB instead ZODB3 and requires ZODB 4+ that is not compatible with Plone5...

So in the meantime, I would like to build a new version based on 3.1 release that fixes the TypeError so it is useable on Plone5.  We would like to adapt various packages to be able to handle "not" ZCatalog queries.

Does that seem correct to you?  Or do you see any other way to use version 3+ with Plone5?

Thank you,

Gauthier

**Comment by icemac** [comment]
What do you think about a 3.1.3 without https://github.com/zopefoundation/Products.ZCatalog/commit/b650b4b7d45410b907d3763a6122925ec7fb9dfe?

**Comment by gbastien** [comment]
Hi @icemac yes that would probably work for us, I just tried version 3.1.2 without direct dependency to ZODB/BTrees and it works on our setup.

Maybe it is just weird that version 3.1.3 has some kind of "regression" compared to 3.1.2 but if it is fine for you, it is for me too :-)

Thank you,

Gauthier

**Comment by icemac** [comment]
@gbastien I just released version 3.1.3 to PyPI: https://pypi.org/project/Products.ZCatalog/3.1.3/ Feel free to try it out.

**Comment by gbastien** [comment]
Great thank you!
