### ISSUE TITLE
"invalid escape sequence" DeprecationWarnings with Python 3.6

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.ZCatalog#49]
`Products.ZCatalog/src/Products/ZCTextIndex/tests/testZCTextIndex.py:242: DeprecationWarning: invalid escape sequence \W
  words = [w for w in re.split('\W+', version.lower())
`

**Comment by dataflake** [comment]
AFAIK most of the time the fix is to mark the regex as raw string (prefix r)

**Comment by jugmac00** [comment]
Thank you. Found official source for that changed behaviour:
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
