### ISSUE TITLE
`PluginIndexes.UnIndex._apply_index` sometimes forgets the intersection with `resultset`

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Products.ZCatalog#55]
There are several weaknesses concerning the `resultset` parameter of `ILimitedResultIndex._apply_index`.

1. The documentation states `The additional resultset argument contains the resultset, as already calculated by ZCatalog's search method.` but does not specify what the index should do with it.

2. `Unindex._apply_index` sometimes intersects its primary result with `resultset` and sometimes forgets to do so -- as shown by the following example (using `Products.ZCatalog==4.2`, but the current master likely has the same problem):
```
>>> from Products.PluginIndexes.unindex import UnIndex
>>> ui = UnIndex("ui")
>>> docs={1:1, 2:2}
>>> for did, e in docs.items(): ui.insertForwardIndexEntry(e, did)
... 
>>> list(ui._apply_index(dict(ui=dict(query=(1,))))[0])
[1]
>>> list(ui._apply_index(dict(ui=dict(query=(1,))), IISet())[0])
[1]
>>> list(ui._apply_index(dict(ui=dict(query=(1,2))))[0])
[1, 2]
>>> list(ui._apply_index(dict(ui=dict(query=(1,2))), IISet())[0])
[]
```
i.e. if we search with a single value, then there is no intersection with `resultset` unlike a search for multiple values.

**Comment by hannosch** [comment]
The resultset is an optional argument the index may use to perform its job. If the index logic can be more efficient by taking a pre-existing result into account, it may use the resultset. The API so far doesn't require the index to do anything with the resultset.

The intersection or weighted intersection of multiple index results happens inside the `catalog._search_index` method.

**Comment by d-maurer** [comment]
Hanno Schlichting wrote at 2019-3-9 13:20 -0800:
>The resultset is an optional argument the index may use to perform its job. If the index logic can be more efficient by taking a pre-existing result into account, it may use the resultset. The API so far doesn't require the index to do anything with the resultset.

Thank you for the clarification.
However, the interface documentation should clearly state this.
Otherwise, index authors have no idea what they should/must do with
the argument `resultset`.


At other places, too, the "docstring" information is of poor
quality, e.g. `Products.PluginIndexes.unindex.UnIndex.query_index`:
```
    def query_index(self, record, resultset=None):
        """Search the index with the given IndexQuery object.

        If the query has a key which matches the 'id' of
        the index instance, one of a few things can happen:

          - if the value is a string, turn the value into
            a single-element sequence, and proceed.

          - if the value is a sequence, return a union search.

          - If the value is a dict and contains a key of the form
            '<index>_operator' this overrides the default method
            ('or') to combine search results. Valid values are 'or'
            and 'and'.
```
This obviously has described `_apply_index` before the `query_index`
refactorization and is inadequate for `query_index`.


>The intersection or weighted intersection of multiple index results happens inside the `catalog._search_index` method.

I have verified this. Thus, the inconsitent behaviour of "Unindex.query_index"
(sometimes there is an intersection with resultset and sometimes not)
does not lead to wrong search results.

Nevertheless, "query_index" could profit from a thorough review:
 * it has the "int --> IISet" normalization at 7 different places
 * it stores a value in the cache at 7 different places
 * for "and", it caches a list of sets rather than their intersection
   (maybe in hope that an incoming *resultset* can reduce the
   intersection costs).
   for "or", however, it caches the multiunion (and not the list of sets) -
   neglecting that an incoming *resultset* can reduce the costs
   even more for a large "multiunion" than for the intersection.
