### ISSUE TITLE
Run ZODB cache garbage collection when returning long lazy result sets

### ISSUE THREAD

**Issue by eprigorodov** [zopefoundation/Products.ZCatalog#6]
Background: if `ZCatalog.threshold` is set to non-None value then `ZCatalog.catalog_objects()` calls  `Connection.cacheGC()` after eash `threshold` calls. That helps client code to limit its memory usage during large reindexing operations.

Reading large result sets from `Catalog.search()` can produce problem similar to mass reindexing: storing too many objects in the ZODB cache, overcoming cache size limits and triggering MemoryOverflow.

Let's consider the use case: ZCatalog with >100K entries, a query that returns ~10K results and client code loop that calculates aggregate from values stored in one of metadata columns.

Such a loop instantiates 10K non-persistent "brains" records. Each "brain" record fills its data with the values pulled from metadata columns. Catalog metadata is stored as IOBTree. Reading one document record from IOBTree fetches the whole IOBucket object that contains metadata for up to 60 catalog entries. 100K big IOBTree has average height of two-three layers and fetching one leaf bucket from the tree bottom requires reading also several intermediate buckets.

With uniform distribution most of 10K result records would fetch metadata from different IOBuckets and reading them all will pull the whole metadata IOBTree into ZODB cache.

Proposal: call `Connection.cacheGC()` after instantiating each `ZCatalog.threshold` "brains" records. Use the same mechanism as is used for transaction savepoint during `ZCatalog.catalog_object()`, but do not make transaction savepoints, only run cache garbage collection.

**Comment by eprigorodov** [comment]
Another implementation option: add new ZCatalog control, `read_threshold`, and use it in the way similar to `threshold`, but in read operations only.

**Comment by eprigorodov** [comment]
[Unit tests](https://github.com/eprigorodov/Products.ZCatalog/blob/issue6-cacheGC-on-search/src/Products/ZCatalog/tests/test_zodb.py) that illustrate the problem: `test_unmaintained_search` fetches twice more IOBuckets than is allowed by the default cache size limit, `test_maintained_search` is broken and should be fixed by coming proposal implementation.

**Comment by eprigorodov** [comment]
A sample implementation is [committed](https://github.com/eprigorodov/Products.ZCatalog/commit/c54b19ca5294de06f47a5826e4878fde016e1b4a) to the repository fork, in the branch issue6-cacheGC-on-search. It fixes `test_maintained_search` and ensures that after reading a long query cache size stays within known limit.

Call counting code that was implemented in `ZCatalog.catalog_object()` has been moved into a separate method. `Catalog` calls that method upon each brain record instantiation if it detects that parent object is `ZCatalog`.

**Comment by hannosch** [comment]
Nice work indeed. I merged this as well, via a squashed commit 8ab5ebe.
