### ISSUE TITLE
IZCatalog not complete

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.ZCatalog#80]
IZCatalog does not define getAllBrains, but ZCatalog uses it

getAllBrains was introduced with
https://github.com/zopefoundation/Products.ZCatalog/commit/4283187483784976b2e4d59449535f4f4cd3e0e8

**Comment by jugmac00** [comment]
Having compared `interfaces/Zcatalog` and the `ZCatalog` implementation, I see no pattern for which implemented methods there is an interface - looks kinda random to me.

@icemac or anybody else, maybe you can give a hint. Does it make sense to define an interface for `getAllBrains` or even for all public methods?

**Comment by icemac** [comment]
Having the public method in the interface would be nice as documentation and to see the public ones together at a single page.

I think some are missing because it got forgotten to add them, so feel free to fix this issue.

**Comment by jugmac00** [comment]
Huh, this was already fixed by #104 - thanks @d-maurer
