### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.ZCatalog#90]
Hi,

due to #88 I had to pin ZCatalog to version 5.0.

I am getting errors in my instance with the pinned version (unrelated to #88) and I want to make sure the errors persist with the current version of ZCatalog.

So, could you please make a new release!

Thank you!

**Comment by icemac** [comment]
I just released https://pypi.org/project/Products.ZCatalog/5.0.3/.
